# -*- coding: utf-8 -*-
"""Alzihmeris.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1laKUOGfZFtKo6XGEyJsboLVJkR_CVSEt
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.preprocessing.image import ImageDataGenerator

IMG_SIZE=224
BATCH_SIZE=32

train_datagen = ImageDataGenerator(rescale=1./255,validation_split=0.2)

train_generator=train_datagen.flow_from_directory(
    '/content/drive/MyDrive/Colab Notebooks/AugmentedAlzheimerDataset/Train',
    target_size=(IMG_SIZE,IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='training'
)

val_generator=train_generator=train_datagen.flow_from_directory(
    '/content/drive/MyDrive/Colab Notebooks/AugmentedAlzheimerDataset/Train',
    target_size=(IMG_SIZE,IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='validation'
)

class_indices=train_generator.class_indices
class_names=list(class_indices.keys())
print("class_indices",class_indices)
print("class_names",class_names)

model=keras.Sequential([
    layers.Conv2D(32,(3,3),activation='relu', input_shape=(IMG_SIZE,IMG_SIZE, 3)),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64,(3,3),activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(128,(3,3),activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Flatten(),
    layers.Dense(128,activation='relu'),
    layers.Dense(4,activation='softmax'),
])

model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

model.fit(train_generator,validation_data=val_generator,epochs=5)

model.save('/content/drive/MyDrive/Colab Notebooks/AugmentedAlzheimerDataset/Train/ND.h5')

from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
import matplotlib.pyplot as plt
import numpy as np
model=load_model('/content/drive/MyDrive/Colab Notebooks/AugmentedAlzheimerDataset/Train/ND.h5')
print("model loaded")

test_image_path="/content/drive/MyDrive/Colab Notebooks/AugmentedAlzheimerDataset/Train/ND/00a98422-8b63-47e6-8b8f-9119984d87ee.jpg"
img=image.load_img(test_image_path,target_size=(224,224))
plt.imshow(img)
plt.axis()
plt.show()

img_array=image.img_to_array(img)
img_array=np.expand_dims(img_array,axis=0)
img_array/=255

perdiction=model.predict(img_array)
ind=np.argmax(perdiction[0])
print(class_names[ind])

